### ISSUE TITLE
CosmicCoder - PartyA with Positive UPNL Can Obstruct PartyB from Emergency Closing Position

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-08-symmetrical-judging#17]
CosmicCoder

medium

# PartyA with Positive UPNL Can Obstruct PartyB from Emergency Closing Position
## Summary

When PartyA has a positive UPNL, it can deallocate a large amount of funds. This can go to the extent that PartyA no 
longer has enough allocated funds to pay back their losses to PartyB. As a result, PartyB, which has positions with 
PartyA, is prevented from emergency-closing profitable positions. This issue arises from an underflow error in the 
LibQuote.closeQuote method.

## Vulnerability Detail

Consider the following scenario: A user holds multiple positions with two PartyBs. Users' positions with one of these PartyBs
is highly profitable for the user, resulting in a significantly positive UPNL. The user can then
deallocate a large amount of funds based on this positive UPNL. Below is the code for fund deallocation:

```ts
function deallocate(uint256 amount, SingleUpnlSig memory upnlSig) internal
{
  AccountStorage.Layout
  storage
  accountLayout = AccountStorage.layout();
  require(
    accountLayout.allocatedBalances[msg.sender] >= amount,
    "AccountFacet: Insufficient allocated balance"
  );
  LibMuon.verifyPartyAUpnl(upnlSig, msg.sender);
  int256
  availableBalance = LibAccount.partyAAvailableForQuote(upnlSig.upnl, msg.sender);
  require(availableBalance >= 0, "AccountFacet: Available balance is lower than zero");
  require(uint256(availableBalance) >= amount, "AccountFacet: PartyA will be liquidatable");

  accountLayout.partyANonces[msg.sender] += 1;
  accountLayout.allocatedBalances[msg.sender] -= amount;
  accountLayout.balances[msg.sender] += amount;
  accountLayout.withdrawCooldown[msg.sender] = block.timestamp;
}
```

Following this deallocation, Another PartyB which has a profitable position with that user is unable to emergency close
the position (which is profitable for PartyB). The error happens in the following line within the `closeQuote` method:

```ts
function closeQuote(Quote storage quote, uint256 filledAmount, uint256 closedPrice) internal
{
  //...
  if (hasMadeProfit) {
    accountLayout.allocatedBalances[quote.partyA] += pnl;
    accountLayout.partyBAllocatedBalances[quote.partyB][quote.partyA] -= pnl;
  } else {
    accountLayout.allocatedBalances[quote.partyA] -= pnl;  // This line will throw an error!
    accountLayout.partyBAllocatedBalances[quote.partyB][quote.partyA] += pnl;
  }
  //..
}
```

## Impact

PartyBs may find themselves unable to initiate emergency closures of positions in emergency situations.

## Tool used

Manual Review

## Recommendation

Not provided

**Comment by CosmicCoder011** [comment]
Duplicated issues get no reward ?!!
