### ISSUE TITLE
Hama - Protocol assumes 18 decimals collateral

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-08-symmetrical-judging#25]
Hama

high

# Protocol assumes 18 decimals collateral
## Summary
This report identifies a calculation issue in the deposit function of a smart contract. The problem arises from assuming a fixed number of decimal places (18) for all collateral tokens , leading to incorrect calculations when interacting with tokens that have a different number of decimals.

## Vulnerability Detail
In the deposit function, the code calculates amountWith18Decimals by multiplying the amount by 1e18 and dividing by 10 raised to the power of the token's decimals. However, this calculation assumes that all tokens have 18 decimals, which may not be the case for some tokens. Here's the problematic code snippet:

    uint256 amountWith18Decimals = (amount * 1e18) / (10 ** IERC20Metadata(appLayout.collateral).decimals());

## Impact
The impact of this issue is significant, especially when interacting with tokens that have a different number of decimals.
 amountWith18Decimals would be bigger in case of vollateral being usdc, wich it s decimals s 1e6, and low for  YAMv2 that  has 24 decimals.

As this s implemented in deposit and withdraw, and called in the external functions of AccountFacet, in deposit, depositFor, withdraw, withdrawto, this will lead to inaccurate collateral ratio calculations, leading to loss of funds to users and  excess token withdrawals to others .

## Code Snippet
https://github.com/sherlock-audit/2023-08-symmetrical/blob/main/symmio-core/contracts/facets/Account/AccountFacetImpl.sol#L23

    
    function deposit(address user, uint256 amount) internal {
        ..
        uint256 amountWith18Decimals = (amount * 1e18) /
        (10 ** IERC20Metadata(appLayout.collateral).decimals());
         ..
    }

https://github.com/sherlock-audit/2023-08-symmetrical/blob/main/symmio-core/contracts/facets/Account/AccountFacetImpl.sol#L36

    function withdraw(address user, uint256 amount) internal {
        ..
        uint256 amountWith18Decimals = (amount * 1e18) /
        (10 ** IERC20Metadata(appLayout.collateral).decimals());
        ..
    }

https://github.com/sherlock-audit/2023-08-symmetrical/blob/main/symmio-core/contracts/facets/Account/AccountFacet.sol#L16
https://github.com/sherlock-audit/2023-08-symmetrical/blob/main/symmio-core/contracts/facets/Account/AccountFacet.sol#L21
https://github.com/sherlock-audit/2023-08-symmetrical/blob/main/symmio-core/contracts/facets/Account/AccountFacet.sol#L26
https://github.com/sherlock-audit/2023-08-symmetrical/blob/main/symmio-core/contracts/facets/Account/AccountFacet.sol#L31

## Tool used
Manual Review

## Recommendation
 determine the number of decimals of the collateral token  and use it in the calculation of amountWith18Decimals.

**Comment by panprog** [comment]
Escalate

This is not dup of #15, it's simply invalid, because it talks about incorrect decimals for deposit and withdraw, while in fact it's correct (because 18 decimals are assumed for internal protocol accounting (internal account balances), not for token, so the conversion from token decimals to internal representation is correct)

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This is not dup of #15, it's simply invalid, because it talks about incorrect decimals for deposit and withdraw, while in fact it's correct (because 18 decimals are assumed for internal protocol accounting (internal account balances), not for token, so the conversion from token decimals to internal representation is correct)

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
> Escalate
> 
> This is not dup of #15, it's simply invalid, because it talks about incorrect decimals for deposit and withdraw, while in fact it's correct (because 18 decimals are assumed for internal protocol accounting (internal account balances), not for token, so the conversion from token decimals to internal representation is correct)

Agree with escalation, this is invalid

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique 
Not a valid issue based on the above comments

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [panprog](https://github.com/sherlock-audit/2023-08-symmetrical-judging/issues/25/#issuecomment-1723370504): accepted
